'use client';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from '../styles/Modules/Home.module.scss'
import React, { useState, useEffect } from 'react'
import Footer from './components/footer/footer'
import Menu from './components/menu/page';
import { Search, getContent } from '@/app/api/api';
import { Content } from '@/app/api/api';
import { CardData } from './Function/Cards/types';
import { generateCards } from './Function/Cards/[search]/generateCards';
import { useRouter } from 'next/navigation';

export default function Home() 
{

  const [content, setContent] = useState<CardData[]>([]);
  const [searchTerm, setSearchTerm] = useState('');

  const[search, setSearch] = useState<Search>({
      search: '',
  })
  
  const handleClearClick = () => {
    setSearchTerm('');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu/>
          <section className={styles.section}>
               <div className={styles.img}>
                  <Image src="/IContentImg.png" alt='icontentPesquisa' width={500} height={200} />
                </div>
              <div className={styles.search}>
                 <div className={styles.icon}></div>
                 <div className={styles.meio}>
                    <input className={styles.input} value={searchTerm} 
                    type={'text'} placeholder="Pesquisar..." 
                    onChange={(e) => setSearchTerm(e.target.value)}/>
                    <span className={styles.clear} onClick={handleClearClick}></span>
                 </div>
              </div>
          </section>

          <section className={styles.text}>
              <p>Educação é uma prática social que visa ao desenvolvimento do ser humano, de suas<br></br>  
                 potencialidades, habilidades e competências A educação, portanto, não se<br></br>
                 restringe a escola.  O ensino é um direito de todos e visa ao pleno<br></br>
                 desenvolvimento humano por meio do processo de ensino e<br></br> 
                 aprendizagem.</p>
          </section>
          <Footer/>
      </main>
    </>
  )
}